config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :books, :authors
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'welcome#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/shelf', to: 'users#shelf'
  post '/shelf', to: 'users#shelf'
  get '/users/:id/most_recent_book', to: 'books#most_recent_book', as: '/most_recent_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :users, through: :books
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  include ApplicationHelper
  belongs_to :user
  belongs_to :author
  validates_presence_of :title, :author
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
    include ApplicationHelper
    has_secure_password validations: false
    has_many :books
    has_many :authors, through: :books
    validates_presence_of :name
    validates_presence_of :password, :if => :should_have_password?

    def self.find_or_create_with_omniauth(auth)
        auth_name = auth["extra"]["raw_info"]["login"]
        user = User.find_by(name: auth_name)

        if user == nil
            user = create(name: auth_name, provider: auth["provider"])
        end

        user
    end

    def should_have_password?
        provider.to_s.strip.empty?
    end 

    def most_recent_book
        self.books.last
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def current_book
        @book = Book.find(params[:id])
    end

    def logged_in?
        current_user
        if !current_user
            redirect_to login_path
        end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :logged_in?
    before_action :current_book, only: [:show, :edit, :update, :destroy]
    
    def new
        @book = Book.new
    end

    def create
        @book = Book.create(book_params.except(:author))
        @author = Author.find_or_create_by(name: book_params[:author])
        @book.update(author_id: @author.id, user_id: @user.id)
        if @book.save
            redirect_to user_book_path(@user, @book)
        else
            render 'new'
        end
    end

    def index
    end

    def show
    end

    def edit
        @author = @book.author
    end
    
    def update
        @author = Author.find_or_create_by(name: book_params[:author])
        @book.update(book_params.except(:author))

        if !@book.errors.empty? || !@author.errors.empty?
            render :action => 'edit'
        elsif @book.author_id != @author.id
            @book.update(author_id: @author.id)
            redirect_to user_book_path(@user, @book)
        else
            redirect_to user_book_path(@user, @book)
        end
    end

    def most_recent_book
        @book = current_user.most_recent_book
        render :action => 'show'
    end

    def destroy
        @book.destroy
        redirect_to user_books_path(@user)
    end
    
    private

    def book_params
        params.require(:book).permit(:title, :author, :pub_year, :note, :favorite)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render 'login'
    end

    def create
        # available when coming back from github
        auth = request.env["omniauth.auth"]
    
        if auth
            omniauth_login_or_create(auth)
        else
            login_with_name_password
        end
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def omniauth_login_or_create(auth)
        @user = User.find_or_create_with_omniauth(auth)
        session[:user_id] = @user.id
        redirect_to user_books_path(@user)
    end

    def login_with_name_password
        @user = User.find_by(name: params[:user][:name])
        if @user == nil
            flash[:none] = "That name does not exist. Please try again."
            redirect_to '/login'
        elsif @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_books_path(@user)
        else
            flash[:incorrect] = "That password is incorrect. Please try again."
            redirect_to '/login'
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in?, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if !@user.errors.empty?
            render :action => 'new'
          else
            session[:user_id] = @user.id
            redirect_to user_books_path(@user)
          end
    end

    def show
    end

    def edit
    end

    def update
        if user_params[:name] == @user.name && @user.authenticate(user_params[:password]) 
            flash[:no_changes] = "You did not make any changes. Please try again."
            redirect_to edit_user_path(@user)
            return
        end
        @user.update(user_params)
        if !@user.errors.empty?  
            render :action => 'edit'
        else
            redirect_to user_path(@user)
        end
    end

    def destroy
        @user.destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
            redirect_to user_books_path(@user)
        else
            render :index
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_display(object, created_or_updated)
        if created_or_updated == "created"
            object.created_at.strftime("%m-%d-%Y")
        elsif created_or_updated == "updated"
            object.updated_at.strftime("%m-%d-%Y")
        end
    end

    def time_display(object, created_or_updated)
        if created_or_updated == "created"
            created_time = object.created_at.in_time_zone("EST")
            created_time.strftime("%I:%M %p %Z")
        elsif created_or_updated == "updated"
            updated_time = object.updated_at.in_time_zone("EST")
            updated_time.strftime("%I:%M %p %Z")
        end
    end
end

app/views/books/_book.html.erb
<div>
    <%= @form.label :title %>
    <%= @form.text_field :title %><br>
    <%= @form.label :author %>
    <%= @form.text_field :author, :value => book ? book.author.name : "" %><br>
    <%= @form.label :pub_year %>
    <%= @form.number_field :pub_year %><br>
    <%= @form.label :note %> 
    <%= @form.text_field :note %><br>
    <%= @form.label :favorite %>
    <%= @form.check_box :favorite %><br><br>
    <%= @form.submit %>
</div>

app/views/books/edit.html.erb
<h1>Editing <i><%= @book.title %></i></h1>
<%= render 'shared/form_errors', object: @book, object_name: "book", action: "updated" %>

<%= render 'shared/form_errors', object: @author, object_name: "author", action: "updated" %>

<%= form_for [@user, @book] do |f| %>
    <% @form = f %>
    <%= render 'book', action: "edit", book: @book %>
<% end %>
<br>
<%= link_to 'Delete Book', user_book_path(@user, @book), :method => :delete %>
<br><br>
<%= link_to 'Back to Book Info', user_book_path(@user, @book) %>
<br><br>
<%= link_to 'Back to Bookshelf', user_books_path(@user) %>

app/views/books/index.html.erb
<h1>Bookshelf of <i><%= @user.name %></i></h1>
<% if @user.books.empty? %>
    <p>Your shelf is empty :(</p>
<% else %>
    <ul>
    <% @user.books.each do |b| %>
        <li><%= link_to "#{b.title}", user_book_path(@user, b) %> by <%= b.author.name%> <% if b.favorite%>&#9734;<%end%> <% if b.note != "" %>&#9993;<%end%></li> 
        <% end %>
    </ul>
<% end %>
<br>
<%= link_to 'Add a book', new_user_book_path(@user) %>
<br><br>
<%= link_to 'Most recently added book', "/users/#{@user.id}/most_recent_book" %>
<br><br>
<%= link_to 'Account Info', user_path(@user) %>
<br><br>
<%= link_to 'Logout', logout_path %>
<br><br>
<i><small><p>key</p></small></i>
<p>&#9734; <small>= <i>this book is a favorite</i></small></p>
<p>&#9993; <small>= <i>this book has a note</i></small></p>

app/views/books/new.html.erb
<h1>Add a new book to your shelf</h1>
<%= render 'shared/form_errors', object: @book, object_name: "book", action: "added" %>

<%= form_for [@user, @book] do |f| %>
    <% @form = f %>
    <%= render 'book', book: nil %>
<% end %>


<br>
<%= link_to 'Back to Bookshelf', user_books_path(@user) %>

app/views/books/show.html.erb
<h1>Viewing <i><%= @book.title %></i></h1>
    <p>Title: <%= @book.title %></p>
    <p>Author: <%= @book.author.name %></p>
    <% if !@book.pub_year.nil? %>
    <p>Publication Year: <%= @book.pub_year %></p>
    <% end %>
    <% if @book.note != "" %>
        <p>&#9993; : <%= @book.note %></p>
    <% end %>
    <% if @book.favorite %>
        <p>&#9734; : this book is a favorite</p>
    <% end %>
    <p>Created on <%= @book.date_display(@book, "created") %> at <%= @book.time_display(@book, "created")  %></p>
    <p>Updated on <%= @book.date_display(@book, "updated") %> at <%= @book.time_display(@book, "updated")  %></p>
<br>
<%= link_to 'Edit', edit_user_book_path(@user, @book) %>
<br><br>
<%= link_to 'Back to Bookshelf', user_books_path(@user) %>
<br><br>
<%= link_to 'Logout', logout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield :form_errors %>
  <div>
    <% flash.keys.each do |type| %>
      <div data-alert class="flash">
        <%= flash[type] %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<div>
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      The following <%= pluralize(object.errors.count, "error") %> prevented your <%= object_name %> from being <%= action %>:
    </h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/users/_user.html.erb
<div>
    <%= @form.label :name %>
    <%= @form.text_field :name %><br>
    <%= @form.label :password %>
    <%= @form.password_field :password %><br><br>
    <%= @form.submit %>
</div>

app/views/users/edit.html.erb
<h1>Edit Info for <i><%= @user.name %></i></h1>
<%= render 'shared/form_errors', object: @user, object_name: "account", action: "updated" %>

<%= form_for @user do |f| %>
    <% @form = f %>
    <%= render 'user' %>
<% end %>
<p>NOTE: if you want to keep your password but change your name, re-enter your password</p>
<br><br>
<%= link_to 'Delete Account', user_path(@user), :method => :delete %>

<br><br>
<%= link_to 'Back to Account Info', user_path(@user) %>
<br><br>
<%= link_to 'Your Bookshelf', user_books_path(@user) %>
<br><br>
<%= link_to 'Logout', logout_path %>

app/views/users/new.html.erb
<h1>Signup for your Bookshelf</h1>
<%= render 'shared/form_errors', object: @user, object_name: "account", action: "created" %>

<%= form_for @user do |f| %>
    <% @form = f %>
    <%= render 'user' %>
<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<h1>Account Info for <i><%= @user.name %></i></h1>
<br>
<p>Name: <%= @user.name %></p>
<p>Password: not shown (click edit link below to change)</p>
<p>Created on <%= @user.date_display(@user, "created") %> at <%= @user.time_display(@user, "created")  %></p>
<p>Updated on <%= @user.date_display(@user, "updated") %> at <%= @user.time_display(@user, "updated")  %></p>
<br>
<%= link_to 'Edit', edit_user_path(@user) %>
<br><br>
<%= link_to 'Back to Bookshelf', user_books_path(@user) %>
<br><br>
<%= link_to 'Logout', logout_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the Bookshelf</h1>
<br>
<%= link_to 'Signup', signup_path %>
<br><br>
<%= link_to 'Login', login_path %>
<br><br>
<%= link_to "Login with Github", "/auth/github" %>